### ISSUE TITLE
compareTo should not be used

### ISSUE THREAD

**Issue by nicolas-chan-42** [howardchanth/2396_A3#1]
https://github.com/howardchanth/2396_A3/blob/7da0333e604f6673ef8293fcca7583f4cfdb5199/src/FullHouse.java#L44

`compareTo(...)` method returns `0` if and only if two cards being compared are _equal in both **rank** and **suit**_.

Do you think this is likely to happen under normal circumstances?

**Comment by howardchanth** [comment]
Corrected this and other classes having the same issue. Thanks~
